### ISSUE TITLE
Addon Manager

### ISSUE THREAD

**Issue by MizukiBelhi** [Crevox/TOSAddon#1]
Please add your addons to the [Addon Manager](https://github.com/JTosAddon/Tree-of-Savior-Addon-Manager).
Thank you!

**Comment by Crevox** [comment]
https://github.com/JTosAddon/Addons/pull/77

Please let me know if I missed anything.

**Comment by MizukiBelhi** [comment]
Don't forget to create your releases.

**Comment by Crevox** [comment]
Should be fixed now, sorry. Wasn't aware that was part of the process.

**Comment by MizukiBelhi** [comment]
No worries! Just had this the other day
![](https://i.gyazo.com/d3e8750bb13887532e52ca321309c5f3.png)
